version: '3.9'
services:
  app:
    container_name: brachio_backend
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - .:/app

#     networks:
#       - default

#   db:
#     container_name: brachio_db
#     build:
#       context: .
#       dockerfile: db.Dockerfile
#     tty: true
#     command: --default-authentication-plugin=mysql_native_password
#     ports:
#       - 3306:3306
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: "test"
#       MYSQL_USER: "tester"
#       MYSQL_PASSWORD: "password"
#     volumes:
#       - type: volume
#         source: mysql_data
#         target: /var/lib/mysql
#     networks:
#       - default

# networks:
#   default:
# volumes:
#   mysql_data:
