name: CI/CD
 
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: 'ap-southeast-2'
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            975050196014.dkr.ecr.ap-southeast-2.amazonaws.com/last-tamushun-be:${{ github.sha }}